export { default as Block } from './Block'
export { default as ContainerFlex } from './ContainerFlex'
export { default as Features } from './Features'
export { default as Footer } from './Footer'
export { default as Headline } from './Headline'
export { default as Image } from './Image'
export { default as InstagramFollowButton } from './InstagramFollowButton'
export { default as PageHead } from './PageHead'
export { default as Pricing } from './Pricing'
export { default as SignupBlock } from './SignupBlock'
export { default as SignupForm } from './SignupForm'
export { default as SocialFollow } from './SocialFollow'
export { default as SocialSharing } from './SocialSharing'
export { default as Testimonials } from './Testimonials'
export { default as Video } from './Video'

// export { googlePageview, googleEvent } from './GoogleAnalytics'
